# Build tinywl every time a commit is pushed to master or
# a pull request is opened against master.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: voidlinux

jobs:
  default_build:
    name: default build
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux:latest

    steps:
      - name: install deps
        run: |
          xbps-install -S
          xbps-install -uy xbps
          # wlroots dependencies as well as we build from source
          xbps-install -uy MesaLib-devel libseat-devel eudev-libudev-devel libdrm-devel \
            libinput-devel libxkbcommon-devel pixman-devel wayland-devel wayland-protocols \
            xcb-util-errors-devel xcb-util-wm-devel xcb-util-renderutil-devel libxcb-devel \
            xcb-util-cursor-devel xcb-util-devel xcb-util-image-devel xcb-util-keysyms-devel \
            xcb-util-xrm-devel xorg-server-xwayland pkg-config meson git gcc \
            zig pkgconf scdoc

          git clone https://github.com/swaywm/wlroots.git
          cd wlroots
          git checkout 0.14.0
          meson build --auto-features=enabled -Dexamples=false -Dwerror=false -Db_ndebug=false
          ninja -C build install
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          cd tinywl
          zig build

  zig_fmt:
    name: zig fmt
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux:latest

    steps:
      - name: install deps
        run: |
          xbps-install -S
          xbps-install -uy xbps
          xbps-install -uy zig git

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: fmt
        run: |
          zig fmt --check src/
          zig fmt --check tinywl/
